[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.26"

[features]
resolution = true
skip-lint = false

[programs.localnet]
tabula_markets = "GZ6F2Q5DWQopyxcyTQk7Jko58Fc9jPdEdGdfiSZS7Z9T"
txline_mock    = "9zs9jxdsjQigoKYpUuUYfBz5fdym3xXgdQa4twEjCYr"

[programs.devnet]
tabula_markets = "GZ6F2Q5DWQopyxcyTQk7Jko58Fc9jPdEdGdfiSZS7Z9T"
txline_mock    = "9zs9jxdsjQigoKYpUuUYfBz5fdym3xXgdQa4twEjCYr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet  = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
  "programs/tabula-markets",
  "programs/txline-mock"
]
