[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.26"

[features]
resolution = true
skip-lint = false

[programs.localnet]
tabula_markets = "Fd6fiHspckMKwwSDPkJHmnp69sQewApDVd7kQc4zUboR"
txline_mock    = "Cx7NL2thRV167d1PaMUgiARvTwLua34KQ7S5qkTBH4oE"

[programs.devnet]
tabula_markets = "Fd6fiHspckMKwwSDPkJHmnp69sQewApDVd7kQc4zUboR"
txline_mock    = "Cx7NL2thRV167d1PaMUgiARvTwLua34KQ7S5qkTBH4oE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet  = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
  "programs/tabula-markets",
  "programs/txline-mock"
]
